"""Initial migration

Revision ID: 54fc5dc0f211
Revises: 
Create Date: 2024-08-30 23:48:17.549150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fc5dc0f211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provedor', sa.String(length=100), nullable=False),
    sa.Column('rtp', sa.Float(), nullable=True),
    sa.Column('volatilidade', sa.String(length=50), nullable=True),
    sa.Column('potencial', sa.Float(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('melhor_x', sa.Float(), nullable=True),
    sa.Column('melhor_euro', sa.Float(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    # ### end Alembic commands ###
